# This is a basic workflow to help you get started with Actions

name: publish production to ftp

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the production branch
  push:
    branches: [ production ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        
      - name: Deploy ğŸš€
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: data.undp.org
          server-dir: data/
          username: sidsautoupdate@data.undp.org
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: api/
